# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='nap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.Nap'),
        ),
    ]
