# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20170916_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
